/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Metric model module.
 * @module model/Metric
 * @version 1.0.0
 */
class Metric {
    /**
     * Constructs a new <code>Metric</code>.
     * @alias module:model/Metric
     * @param age {Number} 
     * @param BMI {Number} 
     * @param waist {Number} 
     * @param vegfruit {Number} 
     * @param protein {Number} 
     */
    constructor(age, BMI, waist, vegfruit, protein) { 
        
        Metric.initialize(this, age, BMI, waist, vegfruit, protein);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, age, BMI, waist, vegfruit, protein) { 
        obj['age'] = age;
        obj['BMI'] = BMI;
        obj['waist'] = waist;
        obj['vegfruit'] = vegfruit;
        obj['protein'] = protein;
    }

    /**
     * Constructs a <code>Metric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Metric} obj Optional instance to populate.
     * @return {module:model/Metric} The populated <code>Metric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Metric();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
            if (data.hasOwnProperty('BMI')) {
                obj['BMI'] = ApiClient.convertToType(data['BMI'], 'Number');
            }
            if (data.hasOwnProperty('waist')) {
                obj['waist'] = ApiClient.convertToType(data['waist'], 'Number');
            }
            if (data.hasOwnProperty('vegfruit')) {
                obj['vegfruit'] = ApiClient.convertToType(data['vegfruit'], 'Number');
            }
            if (data.hasOwnProperty('protein')) {
                obj['protein'] = ApiClient.convertToType(data['protein'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Metric.prototype['_id'] = undefined;

/**
 * @member {Number} age
 */
Metric.prototype['age'] = undefined;

/**
 * @member {Number} BMI
 */
Metric.prototype['BMI'] = undefined;

/**
 * @member {Number} waist
 */
Metric.prototype['waist'] = undefined;

/**
 * @member {Number} vegfruit
 */
Metric.prototype['vegfruit'] = undefined;

/**
 * @member {Number} protein
 */
Metric.prototype['protein'] = undefined;






export default Metric;

